version: 2.1

orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  build:
    docker:
      - image: circleci/android:3.7.9
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.7.9
      - flutter/install_pub:
          cache-version: v1
      - run:
          name: Flutter clean
          command: flutter clean
      - run:
          name: Print Dart SDK version
          command: dart --version
      - run:
          name: Flutter pub get
          command: flutter pub get
      - run:
          name: Run unit tests
          command: flutter test
      - run:
          name: Build APK
          command: flutter build apk
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
